feat(toolbox): general improvment of some scripts
Add significants error messages in build-streamcluster and
xen-get-home, and remove useless output.
Make a cleanup in the test partition after the experiment to keep only
the log files in streamcluster-1domu

diff --git a/benchmark/toolbox/expe/streamcluster-1domu b/benchmark/toolbox/expe/streamcluster-1domu
--- a/benchmark/toolbox/expe/streamcluster-1domu
+++ b/benchmark/toolbox/expe/streamcluster-1domu
@@ -1,4 +1,6 @@
 #!/bin/sh
+# Run streamcluster on a Xen virtual machine (domU) with almost the ressources
+# of the native machine (in terms of vcpus and memory).
 
 error() {
     MSG=$1; shift
@@ -11,7 +13,8 @@ VMNAME=xen-vm-0
 RESULTS=`date +'%Y-%m-%d-%H-%M-%S'`
 
 mkdir "$RESULTS" || error "cannot mkdir '$RESULTS'"
-mkdir "$RESULTS/tools" || exit 1
+mkdir "$RESULTS/tools" || error "cannot mkdir '$RESULTS/tools'"
+mkdir "$RESULTS/log" || error "cannot mkdir '$RESULTS/logs'"
 
 build-streamcluster "$RESULTS/parsec" || exit 1
 cp `which streamcluster` "$RESULTS/tools"
@@ -30,17 +33,21 @@ xen-login "$VMNAME"
 (
     echo 'cd /home'
     echo 'PATH=$PATH:$PWD/tools'
-    echo 'cpurate cpu streamcluster &'
-    echo 'memrate mem streamcluster &'
+    echo 'cpurate log/cpu streamcluster &'
+    echo 'memrate log/mem streamcluster &'
     echo 'streamcluster parsec'
-    echo 'kill `cat cpu.pid`'
-    echo 'kill `cat mem.pid`'
-    echo 'rm cpu.pid'
-    echo 'rm mem.pid'
+    echo 'kill `cat log/cpu.pid`'
+    echo 'kill `cat log/mem.pid`'
+    echo 'rm log/cpu.pid'
+    echo 'rm log/mem.pid'
+    echo 'mv `find parsec/log/ -name "*.log"` log'
     echo 'sync'
 ) | xen-command "$VMNAME"
 
 xen-shutdown "$VMNAME"
 
 xen-get-home "$VMNAME" "$RESULTS" || exit 1
+mv "$RESULTS/log"/* "$RESULTS"
+rm -rf "$RESULTS/parsec" "$RESULTS/tools"
+rmdir "$RESULTS/log"
 rm -rf "$VMNAME"
