feat(toolbox): add the first auto experiment script
Add a script to perform a complete experiment from the vm creation to
the result get back.
Improved streamcluster related scripts by deploying it into a given
directory and removing all unecessary files of parsec.
Add a xen-clone scrit to perform a cheap copy of a given vm.

diff --git a/benchmark/toolbox/bench/build-streamcluster b/benchmark/toolbox/bench/build-streamcluster
--- a/benchmark/toolbox/bench/build-streamcluster
+++ b/benchmark/toolbox/bench/build-streamcluster
@@ -1,13 +1,27 @@
 #!/bin/sh
 
+error() {
+    MSG=$1; shift
+    echo "$0: $MSG" 1>&2
+    exit 1
+}
+
 ADDR="http://parsec.cs.princeton.edu/download/3.0/parsec-3.0-core.tar.gz"
 TARZ="parsec.tar.gz"
 PARS="parsec-3.0"
+DEST=$1 ; shift
+[ "x$DEST" == "x" ] && DEST='parsec'
 
-cd /tmp || exit 1
-[ -e "$TARZ" ] || curl "$ADDR" > "$TARZ" || exit 1
-tar -xzf "$TARZ" || exit 1
+prev="$PWD"
+mkdir "$DEST" || error "cannot create '$DEST'"
+cd "$DEST"
+[ -e "/tmp/$TARZ" ] || curl "$ADDR" >"/tmp/$TARZ" \
+    || error "cannot download '$ADDR'"
+[ -e env.sh ] || tar -xzf "/tmp/$TARZ" || error "cannot extract '$TARZ'"
+[ -e env.sh ] || mv "$PARS/"* "$PARS"/.* . 2>/dev/null
+[ -e env.sh ] || rmdir "$PARS"
 
-cd "$PARS" || exit 1
-source ./env.sh || exit 1
-parsecmgmt -a build -p streamcluster || exit 1
+source ./env.sh || error "cannot find 'env.sh'"
+parsecmgmt -a build -p streamcluster || error "cannot build"
+rm -rf ext pkgs/apps pkgs/netapps pkgs/tools pkgs/libs
+cd "$prev"
diff --git a/benchmark/toolbox/bench/streamcluster b/benchmark/toolbox/bench/streamcluster
--- a/benchmark/toolbox/bench/streamcluster
+++ b/benchmark/toolbox/bench/streamcluster
@@ -1,8 +1,15 @@
 #!/bin/sh
 
-PARS="parsec-3.0"
-CPUS=48
+error() {
+    MSG=$1; shift
+    echo "$0: $MSG" 1>&2
+    exit 1
+}
 
-cd "/tmp/$PARS" || exit 1
-source ./env.sh || exit 1
-parsecmgmt -a run -p streamcluster -n $CPUS -i native || exit 1
+PARS=$1; shift
+[ "x$PARS" == "x" ] && PARS='parsec'
+CPUS=2
+
+cd "$PARS" || error "cannot find '$PARS'"
+source ./env.sh || error "cannot find 'env.sh'"
+parsecmgmt -a run -p streamcluster -n $CPUS -i simlarge
